python ./src/dynaprog/run_latent.py \
    --base_model ./models/Qwen2.5-1.5B \
    --data_path ./data/dynaprog/dp_data.json \
    --save_model_path ./models/dynaprog/latent_row/Qwen2.5-1.5B \
    --save_result_path ./results/dynaprog/latent_row/Qwen2.5-1.5B \
    --latent_dim 50 \
    --compress row \
    --do_train \
    --learning_rate 1e-5 \
    --weight_decay 0 \
    --grad_clip 1.0 \
    --train_batch_size 4 \
    --epoch 1 \
    --logging_steps 200 \
    --max_new_tokens 1024 \
    --seed 42