python ./src/multiplication/run_cot.py \
    --base_model ./models/Qwen2.5-1.5B \
    --data_path ./data/multiplication/4_mul_4.json \
    --save_model_path ./models/multiplication/compressed_cot/Qwen2.5-1.5B \
    --save_result_path ./results/multiplication/compressed_cot/Qwen2.5-1.5B \
    --do_train \
    --learning_rate 1e-5 \
    --weight_decay 0 \
    --grad_clip 1.0 \
    --train_batch_size 4 \
    --epoch 1 \
    --logging_steps 200 \
    --cot_type compressed \
    --max_new_tokens 1024 \
    --seed 42